version: "3.7"
services:
    devops-demo-postgres:
        container_name: devops-demo-postgres
        build:
            context: ./postgres
        image: "localhost/devops-demo-postgres:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "500M"
        environment:
            - POSTGRES_PASSWORD=devops
        volumes:
            - devops-demo-postgres-storage:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - devops-demo-net
    
    devops-demo-cadvisor:
        container_name: devops-demo-cadvisor
        build:
            context: ./cadvisor
        image: "localhost/devops-demo-cadvisor:0.0.1"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "500M"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        command: --url_base_prefix=/cadvisor
        networks:
            - devops-demo-net

    devops-demo-prometheus:
        container_name: devops-demo-prometheus
        build:
            context: ./prometheus
        image: "localhost/devops-demo-prometheus:0.0.1"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "500M"
        # do not add "--web.route-prefix"
        # https://github.com/prometheus/prometh2433185eus/issues/4925#issuecomment-44
        command: --config.file=/etc/devops-demo.yaml --web.external-url=https://localhost/prometheus
        volumes:
            - devops-demo-prometheus-storage:/prometheus
        networks:
            - devops-demo-net

    devops-demo-keycloak:
        container_name: devops-demo-keycloak
        build:
            context: ./keycloak
        image: "localhost/devops-demo-keycloak:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "750M"
        depends_on:
            - devops-demo-postgres
        environment:
            - KEYCLOAK_USER=keycloak
            - KEYCLOAK_PASSWORD=devops
            - DB_VENDOR=postgres
            - DB_ADDR=devops-demo-postgres
            - DB_PORT=5432
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=devops
            - PROXY_ADDRESS_FORWARDING=true
            - KEYCLOAK_FRONTEND_URL=https://localhost/auth/
        networks:
            - devops-demo-net

    devops-demo-sonarqube:
        container_name: devops-demo-sonarqube
        build:
            context: ./sonarqube
        image: "localhost/devops-demo-sonarqube:0.0.1"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1500M"
        depends_on:
            - devops-demo-postgres
        environment:
            - sonar.jdbc.username=sonarqube
            - sonar.jdbc.password=devops
            - sonar.jdbc.url=jdbc:postgresql://devops-demo-postgres:5432/sonarqube
        volumes:
            - devops-demo-sonarqube_conf:/opt/sonarqube/conf
            - devops-demo-sonarqube_extensions:/opt/sonarqube/extensions
            - devops-demo-sonarqube_logs:/opt/sonarqube/logs
            - devops-demo-sonarqube_data:/opt/sonarqube/data
        networks:
            - devops-demo-net

    devops-demo-nginx:
        container_name: devops-demo-nginx
        build:
            context: ./nginx
        image: "localhost/devops-demo-nginx:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "100M"
        ports:
            - "443:443"
        networks:
            - devops-demo-net
networks:
    devops-demo-net:
        driver: bridge

volumes:
    devops-demo-postgres-storage:
    devops-demo-sonarqube_conf:
    devops-demo-sonarqube_extensions:
    devops-demo-sonarqube_logs:
    devops-demo-sonarqube_data:
    devops-demo-prometheus-storage:
