version: "3.7"
services:
    devops-demo-postgres:
        container_name: devops-demo-postgres
        build:
            context: ./postgres
        image: "localhost/devops-demo-postgres:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "500M"
        volumes:
            - postgres-storage:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=devops
        networks:
            - devops-demo-net

    devops-demo-nginx:
        container_name: devops-demo-nginx
        build:
            context: ./nginx
        image: "localhost/devops-demo-nginx:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "100M"
        #depends_on:
         #   - sonarqube
        ports:
            - "443:443"
        networks:
            - devops-demo-net
networks:
    devops-demo-net:
        driver: bridge

volumes:
    postgres-storage:
