version: "3.7"
services:
    devops-demo-postgres:
        container_name: devops-demo-postgres
        build:
            context: ./postgres
        image: "localhost/devops-demo-postgres:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "500M"
        volumes:
            - devops-demo-postgres-storage:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=devops
        networks:
            - devops-demo-net

    devops-demo-sonarqube:
        container_name: devops-demo-sonarqube
        build:
            context: ./sonarqube
        image: "localhost/devops-demo-sonarqube:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1500M"
        depends_on:
            - devops-demo-postgres
        environment:
            - sonar.jdbc.username=sonarqube
            - sonar.jdbc.password=devops
            - sonar.jdbc.url=jdbc:postgresql://devops-demo-postgres:5432/sonarqube
        volumes:
            - devops-demo-sonarqube_conf:/opt/sonarqube/conf
            - devops-demo-sonarqube_extensions:/opt/sonarqube/extensions
            - devops-demo-sonarqube_logs:/opt/sonarqube/logs
            - devops-demo-sonarqube_data:/opt/sonarqube/data
        networks:
            - devops-demo-net

    devops-demo-nginx:
        container_name: devops-demo-nginx
        build:
            context: ./nginx
        image: "localhost/devops-demo-nginx:0.0.1"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "100M"
        depends_on:
            - devops-demo-sonarqube
        ports:
            - "443:443"
        networks:
            - devops-demo-net
networks:
    devops-demo-net:
        driver: bridge

volumes:
    devops-demo-postgres-storage:
    devops-demo-sonarqube_conf:
    devops-demo-sonarqube_extensions:
    devops-demo-sonarqube_logs:
    devops-demo-sonarqube_data: